; задание 2
; (print (caadr '((blue cube) (red pyramid))))
; (print (cdar '((abc)(def)(ghi))))
; (print (cadr '((abc)(def)(ghi))))
; (print (caddr '((abc)(def)(ghi))))
; задание 3
; (print (list 'Fred 'and 'Wilma))
; (print (list 'Fred '(and Wilma)))
; (print (cons Nil Nil))
; (print (cons T Nil))
; (print (cons Nil T))
; (print (list Nil))
; (print (list '(one two) '(free temp)))
; (print (cons 'Fred '(and Wilma)))
; (print (cons 'Fred '(Wilma)))
; (print (cons '(T) Nil))
; (print (list Nil Nil))
; (print (list T Nil))
; (print (list Nil T))
; (print (cons T (list Nil)))
; (print (list '(T) Nil))
; (print (cons '(one two) '(free temp)))
; задание 4
; (print (list (list 'ar1 'ar2) (list 'ar3 'ar4)))
; (print (list (list 'ar1) (list 'ar2)))
; (print (list (list (list 'ar1))))
; доп задание
(print (cons 'a (cons 'b (cons 'c Nil))))
(print (list 'a 'b 'c))